---
name: "Test"

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@2.0.2
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: "lint-unit"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - amazonlinux-2
          - debian-9
          - debian-10
          - debian-11
          - centos-7
          - centos-8
          - ubuntu-1804
          - ubuntu-2004
        suite:
          - openjdk-11
          - openjdk-16
          - openjdk-17
          - adoptopenjdk-8-openj9
          - adoptopenjdk-11-hotspot
          - adoptopenjdk-11-openj9
          - adoptopenjdk-11-openj9-large-heap
          - adoptopenjdk-14-hotspot
          - adoptopenjdk-14-openj9
          - adoptopenjdk-14-openj9-large-heap
          - adoptopenjdk-removal-11-openj9
          - corretto-8
          - corretto-11
          - corretto-17
          - corretto-18
          - custom-package-8
          - custom-package-11
          - custom-package-11-openj9
          - custom-package-11-openj9-large-heap
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install Chef
        uses: actionshub/chef-install@2.0.4
      - name: Dokken
        uses: actionshub/test-kitchen@2.1.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}

  integration-macos:
    needs: "lint-unit"
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install Chef
        uses: actionshub/chef-install@2.0.4
      - name: Kitchen Converge
        uses: actionshub/test-kitchen@2.1.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.macos.yml
          TERM: xterm-256color
        with:
          suite: adoptopenjdk-14
          os: macos
          action: converge
      - name: Source Profile for JAVA_HOME
        run: |
          source /etc/profile
          echo "sourced profile for JAVA_HOME"
          echo "New JAVA home after Chef run is: ${JAVA_HOME}"
          # Magic line for github actions to persist the change
          echo "JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
      - name: Kitchen Verify
        uses: actionshub/test-kitchen@2.1.0
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.macos.yml
          TERM: xterm-256color
        with:
          suite: adoptopenjdk-14
          os: macos
          action: verify

  final:
    runs-on: ubuntu-latest
    needs: [integration, integration-macos]
    steps:
      - run: echo ${{needs.integration.outputs}}
      - run: echo ${{needs.integration-macos.outputs}}
